{% set version = "1.9.4" %}

package:
  name: fiona
  version: {{ version }}

source:
  url: https://github.com/Toblerity/Fiona/archive/refs/tags/{{ version }}.zip
  sha256: 5890977e8c038e3869c8b18b468c689ec99f6e7a0c71b34774b3507a98898480

build:
  number: 1
  skip: true  # [win and vc<14]
  script_env:
    - GDAL_ENABLE_DEPRECATED_DRIVER_GTM=YES
  entry_points:
    - fio = fiona.fio.main:main_group

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - certifi  # [py<=37]
    - cython >=0.28.3
    - numpy
    - libgdal
  run:
    - python
    - certifi  # [py<=37]
    - setuptools
    - gdal
    - {{ pin_compatible('numpy') }}
    - attrs >=17
    - click >=4.0
    - cligj >=0.5
    - click-plugins >=1.0
    - importlib-metadata
    - six >=1.7
    - munch
    - shapely  # only option calc we include by default

test:
  source_files:
    - tests
  imports:
    - fiona
    - fiona.fio
  requires:
    - pytest >=3
    - boto3 >=1.2.4
    - packaging
    - pytz
  files:
    - test_data
  commands:
    - fio --help
    - fio ls test_data/test.shp
    - fio info test_data/test.shp

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Fiona reads and writes spatial data files

extra:
  recipe-maintainers:
    - zklaus
    - akrherz
    - ocefpaf
    - jorisvandenbossche
