{% set version = "1.6.3" %}

package:
    name: fiona
    version: {{ version }}

source:
    fn: Fiona-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/F/Fiona/Fiona-{{ version }}.tar.gz
    md5: f6b70e1a30fc8db597c360e375d186de

build:
    number: 1
    skip: True  # [win and py35]
    preserve_egg_dir: True
    entry_points:
        - fio=fiona.fio.main:main_group

requirements:
    build:
        - python
        - cython
        - setuptools
        - numpy x.x
        - gdal ==1.11.4
        - giflib  # [not win]
    run:
        - python
        - setuptools
        - numpy x.x
        - gdal ==1.11.4
        - cligj
        - munch
        - click-plugins
        - six
        - giflib  # [not win]

test:
    imports:
        - fiona
        - fiona.fio
    commands:
        - fio --help
        - conda inspect linkages fiona --name _test  # [linux]
    requires:
        - nose
    files:
        - test.cpg
        - test.dbf
        - test.shp
        - test.shx

about:
    home: http://github.com/Toblerity/Fiona
    license: BSD License
    summary: Fiona reads and writes spatial data files

extra:
    recipe-maintainers:
        - ocefpaf
