{% set version = "1.8.17" %}

package:
  name: fiona
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/F/Fiona/Fiona-{{ version }}.tar.gz
  sha256: 716201c21246587f374785bec6d6a20a984fe1f6c2b0e83bf15127eb8f724d0c

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - fio = fiona.fio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.28.3
    - numpy
    - libgdal
  run:
    - python
    - setuptools
    - gdal
    - {{ pin_compatible('numpy') }}
    - attrs >=17
    - click >=4.0,<8
    - cligj >=0.5
    - click-plugins >=1.0
    - six >=1.7
    - munch
    - argparse  # [py<27]
    - ordereddict  # [py<27]
    - enum34  # [py<34]
    - shapely  # only option calc we include by default

test:
  source_files:
    - tests
  imports:
    - fiona
    - fiona.fio
  requires:
    - pytest >=3
    - boto3 >=1.2.4
    - packaging
    - pytest-catchlog
    - mock  # [py2k]
    - pytz
  files:
    - test_data
  commands:
    - fio --help
    - fio ls test_data/test.shp
    - fio info test_data/test.shp

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Fiona reads and writes spatial data files

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
