{% set version = "1.7.9" %}

package:
  name: fiona
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/F/Fiona/Fiona-{{ version }}.tar.gz
  sha256: 91bb71b744a7444c3d96472158b74af1569ec2bc934737397658b968dd7dadba

build:
  number: 2
  preserve_egg_dir: True
  entry_points:
    - fio=fiona.fio.main:main_group

requirements:
  build:
    - python
    - cython
    - setuptools
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - gdal 2.2.*
  run:
    - python
    - setuptools
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - gdal 2.2.*
    - cligj
    - munch
    - click-plugins
    - six
    - enum34  # [py27]
    - shapely

test:
  source_files:
    - tests
  imports:
    - fiona
    - fiona.fio
  requires:
    - pytest
  files:
    - test_data
  commands:
    - fio --help
    - fio ls test_data/test.shp
    - fio info test_data/test.shp
    - conda inspect linkages -p $PREFIX fiona  # [not win]
    - conda inspect objects -p $PREFIX fiona  # [osx]

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Fiona reads and writes spatial data files.'

extra:
  recipe-maintainers:
    - ocefpaf
